name: Build and publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Remove not-wanted files in server
        run: "rm -r README.md .git .github"

      - uses: actions/upload-artifact@v4
        name: Upload Artifact
        with:
          name: FindMyAC
          path: "./*"
  
