name: Build Angular

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Remove not-wanted files in server
        run: "rm README.md"

      - uses: actions/upload-artifact@v3
        name: Upload Artifact
        with:
          name: FindMyAC
          path: "./*"
  
      - name: Copy repository contents
        uses: wangyucode/sftp-upload-action@v1.4.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          privateKey: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          localDir: "./"
          remoteDir: "/var/www/findmyac"
          dryRun: false
          exclude: ".git,.github"